[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm@10", "pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node --enable-source-maps ./dist/index.mjs"